include: package:lint/analysis_options.yaml

linter:
  rules:
    argument_type_not_assignable: false

# linter:
#   rules:
#     missing_required_param: true  
#     prefer_const_declarations: true  
#     prefer_const_constructors: true
#     avoid_print: true
#     unnecessary_parenthesis: true
#     prefer_final_locals: true
#     avoid_redundant_argument_values: true
#     curly_braces_in_flow_control_structures: true
#     prefer_const_constructors_in_immutables: true
#     always_declare_return_types: false
#     type_annotate_public_apis: true
#     avoid_unnecessary_container: true
#     # parameter_assignments:true
#     unnecessary_new: true
#     sized_box_for_whitespace: true
#     prefer_const_literals_to_create_immutables: true

# analyzer:
#   errors:
#     missing_required_param: warning
#     prefer_const_declarations: warning
#     prefer_const_constructors: warning
#     avoid_print: warning
#     unnecessary_parenthesis: warning
#     prefer_final_locals: warning
#     always_declare_return_types: warning
#     avoid_redundant_argument_values: warning
#     curly_braces_in_flow_control_structures: warning
#     unnecessary_new: warning 




