/// Flutter icons MyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData home = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
  static const IconData home_active = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
  static const IconData search_active = IconData(
    0xe802,
    fontFamily: _kFontFam,
  );
  static const IconData search = IconData(
    0xe803,
    fontFamily: _kFontFam,
  );
  static const IconData send = IconData(
    0xe804,
    fontFamily: _kFontFam,
  );
  static const IconData comment = IconData(
    0xe805,
    fontFamily: _kFontFam,
  );
  static const IconData settings = IconData(
    0xe806,
    fontFamily: _kFontFam,
  );
  static const IconData qr_code = IconData(
    0xe807,
    fontFamily: _kFontFam,
  );
  static const IconData messenger = IconData(
    0xe808,
    fontFamily: _kFontFam,
  );
  static const IconData new_post = IconData(
    0xe809,
    fontFamily: _kFontFam,
  );
  static const IconData heart_active = IconData(
    0xe80a,
    fontFamily: _kFontFam,
  );
  static const IconData heart = IconData(
    0xe80b,
    fontFamily: _kFontFam,
  );
  static const IconData add = IconData(
    0xe80c,
    fontFamily: _kFontFam,
  );
  static const IconData menu = IconData(
    0xe80d,
    fontFamily: _kFontFam,
  );
  static const IconData bookmarked = IconData(
    0xe80e,
    fontFamily: _kFontFam,
  );
  static const IconData archive = IconData(
    0xe80f,
    fontFamily: _kFontFam,
  );
  static const IconData activity = IconData(
    0xe810,
    fontFamily: _kFontFam,
  );
  static const IconData add_people = IconData(
    0xe811,
    fontFamily: _kFontFam,
  );
  static const IconData star = IconData(
    0xe812,
    fontFamily: _kFontFam,
  );
  static const IconData edit = IconData(
    0xe813,
    fontFamily: _kFontFam,
  );
  static const IconData account = IconData(
    0xe814,
    fontFamily: _kFontFam,
  );
  static const IconData lock_outline = IconData(
    0xe815,
    fontFamily: _kFontFam,
  );
  static const IconData security = IconData(
    0xe816,
    fontFamily: _kFontFam,
  );
  static const IconData notification = IconData(
    0xe817,
    fontFamily: _kFontFam,
  );
  static const IconData payment = IconData(
    0xe818,
    fontFamily: _kFontFam,
  );
  static const IconData info_outline = IconData(
    0xe819,
    fontFamily: _kFontFam,
  );
  static const IconData help = IconData(
    0xe81a,
    fontFamily: _kFontFam,
  );
  static const IconData theme = IconData(
    0xe81b,
    fontFamily: _kFontFam,
  );
  static const IconData videocam = IconData(
    0xe81c,
    fontFamily: _kFontFam,
  );
  static const IconData photo = IconData(
    0xe81d,
    fontFamily: _kFontFam,
  );
  static const IconData camera = IconData(
    0xe826,
    fontFamily: _kFontFam,
  );
  static const IconData bookmark = IconData(
    0xf097,
    fontFamily: _kFontFam,
  );
  static const IconData archive_1 = IconData(
    0xf375,
    fontFamily: _kFontFam,
  );
  static const IconData mic = IconData(
    0xf3c9,
    fontFamily: _kFontFam,
  );
}
